"""
Clustering Analysis for Intrusion Detection
- Loads preprocessed combined features (network + statistical)
- Applies KMeans clustering
- Visualizes with PCA
- Compares clusters with true labels
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score, adjusted_rand_score, normalized_mutual_info_score
import warnings
warnings.filterwarnings('ignore')

# ------------------------------
# 1. Load combined features and labels
# ------------------------------
print("="*80)
print("Loading preprocessed combined features and labels...")
print("="*80)

# Load combined features (generated by your main script)
X = pd.read_csv('combined_features.csv')
print(f"Features shape: {X.shape}")

# Load original labels from the raw data (or from a saved label file)
# We need to align labels with the same rows. Since you saved combined_features.csv without labels,
# we need to load the original labels from the raw combined data before feature extraction.
# Alternatively, we can reload the raw combined data (60k rows) and extract labels.
# Let's do that quickly (it's small).

print("Loading raw combined data to get labels...")
files = {
    '02-14': 'data/02-14-2018.csv',
    '02-16': 'data/02-16-2018.csv',
    '02-21': 'data/02-21-2018.csv'
}
samples = []
for name, path in files.items():
    df = pd.read_csv(path, nrows=20000, low_memory=False)
    samples.append(df)
df_raw = pd.concat(samples, ignore_index=True)
df_raw = df_raw[df_raw['Label'] != 'Label'].copy()
y = df_raw['Label']  # original string labels
print(f"Labels shape: {len(y)}")

# Ensure same number of rows
assert len(X) == len(y), "Mismatch between features and labels"

# ------------------------------
# 2. Scale features for clustering
# ------------------------------
print("\n" + "="*80)
print("Scaling features for clustering...")
print("="*80)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ------------------------------
# 3. Determine optimal number of clusters (elbow method)
# ------------------------------
print("\n" + "="*80)
print("Elbow method for optimal K...")
print("="*80)
inertias = []
sil_scores = []
K_range = range(2, 11)
for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    inertias.append(kmeans.inertia_)
    sil_scores.append(silhouette_score(X_scaled, kmeans.labels_))
    print(f"K={k}: Inertia={kmeans.inertia_:.0f}, Silhouette={sil_scores[-1]:.4f}")

# Plot elbow
plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(K_range, inertias, 'bo-')
plt.xlabel('Number of clusters (K)')
plt.ylabel('Inertia')
plt.title('Elbow Method')

plt.subplot(1,2,2)
plt.plot(K_range, sil_scores, 'ro-')
plt.xlabel('Number of clusters (K)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Score')
plt.tight_layout()
plt.savefig('clustering_elbow.png', dpi=150)
plt.close()
print("Saved: clustering_elbow.png")


best_k = K_range[np.argmax(sil_scores)]
print(f"\nBest K based on silhouette score: {best_k}")

# ------------------------------
# 4. Final clustering with best K
# ------------------------------
print("\n" + "="*80)
print(f"Performing KMeans with K={best_k}...")
print("="*80)
kmeans_final = KMeans(n_clusters=best_k, random_state=42, n_init=10)
cluster_labels = kmeans_final.fit_predict(X_scaled)

# Evaluate against true labels (convert true labels to numeric for ARI and NMI)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)

ari = adjusted_rand_score(y_encoded, cluster_labels)
nmi = normalized_mutual_info_score(y_encoded, cluster_labels)
print(f"Adjusted Rand Index (ARI): {ari:.4f}")
print(f"Normalized Mutual Information (NMI): {nmi:.4f}")

# Show cluster distribution vs true attack types
cluster_df = pd.DataFrame({'True_Label': y, 'Cluster': cluster_labels})
print("\nCluster composition (top 5 per cluster):")
for c in range(best_k):
    print(f"\nCluster {c}:")
    print(cluster_df[cluster_df['Cluster']==c]['True_Label'].value_counts().head(5))

# ------------------------------
# 5. Visualize clusters using PCA
# ------------------------------
print("\n" + "="*80)
print("PCA visualization...")
print("="*80)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(10,8))
scatter = plt.scatter(X_pca[:,0], X_pca[:,1], c=cluster_labels, cmap='tab10', alpha=0.6, s=10)
plt.colorbar(scatter, label='Cluster')
plt.title(f'KMeans Clustering (K={best_k}) - PCA Projection')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.savefig('clustering_pca.png', dpi=150)
plt.close()
print("Saved: clustering_pca.png")

# Also color by true label
plt.figure(figsize=(10,8))
scatter = plt.scatter(X_pca[:,0], X_pca[:,1], c=y_encoded, cmap='tab10', alpha=0.6, s=10)
plt.colorbar(scatter, label='True Attack Class (encoded)')
plt.title('True Labels - PCA Projection')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.savefig('true_labels_pca.png', dpi=150)
plt.close()
print("Saved: true_labels_pca.png")

print("\n" + "="*80)
print("Clustering analysis completed.")
print("="*80)
